### ISSUE TITLE
Setup multi crate release in ci

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia-rs#118]
In `v0.1.6-rc1` we added a multi crate project layout.

Thus, we need to explore how to update the [`rust_release.yaml`](https://github.com/kornia/kornia-rs/blob/main/.github/workflows/rust_release.yml) to resolve the dependencies between the internal creates.

- `kornia-core` is the root
- `kornia-image` depends on `kornia-core`
- `kornia-io` depends on `kornia-image` and `kornia-core`
- `kornia-imgproc` depends on `kornia-image` and `kornia-core`

**Comment by edgarriba** [comment]
@haixuanTao i would like to hear your opinion how you deal with this in dora?

**Comment by haixuanTao** [comment]
Not sure what you mean. We pinned all version in root workspace version
