### ISSUE TITLE
Implement `kornia_imgproc::crop`

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia-rs#139]
Implement a crop function in the kornia imgproc.

- Possibly this requires some sort of slice function in kornia_core::Tensor.
- Evaluate whether this can be implemented as a view

**Comment by csking101** [comment]
Hi, I am new to kornia-rs, do you think this would be a good first issue?

**Comment by edgarriba** [comment]
Hi, I think yes. Yes, feel free to give it a shop reusing the TensorView (or maybe we need an ImageView) struct.

**Comment by edgarriba** [comment]
implemented here https://github.com/kornia/kornia-rs/pull/155

**Comment by edgarriba** [comment]
Feel free to open again if there's any issue
