### ISSUE TITLE
Verify that pyo3 transfer the ownership of the data to python

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia-rs#17]
we want move semantics to happen and avoid copies around the tensor data. @strasdat any thoughts here ?

Context about how we do it now: https://github.com/kornia/kornia-rs/blob/main/src/dlpack_py.rs#L27-L62

It's done via python capsules to match compatibility with dl frameworks implementing dlpack.
See also: https://github.com/kornia/dlpack-rs

However, for some reason i was suggested by some one from the pyo3 community to avoid pycapsules :)

**Comment by carlosb1** [comment]
I think, the first step could be get more information about why pycapsules is not a good practice...
