### ISSUE TITLE
Add M1 version to pypi :)

### ISSUE THREAD

**Issue by ducha-aiki** [kornia/kornia-rs#20]

**Comment by edgarriba** [comment]
any idea what architecture is M1 ? 
https://github.com/kornia/kornia-rs/blob/main/.github/workflows/release.yml#L47

**Comment by ducha-aiki** [comment]
arm64, OS - Darwin

**Comment by edgarriba** [comment]
oh, arm is the next thing. I'll try because i need it for the nvidia jetson soon
