### ISSUE TITLE
Add support to py 3.10

### ISSUE THREAD

**Issue by johnnv1** [kornia/kornia-rs#21]
Related to https://github.com/kornia/kornia/issues/1979

Apparently, `kornia-rs` is not available for python3.10

**Comment by edgarriba** [comment]
i can take this action

**Comment by johnnv1** [comment]
can we also try to have a release for 3.11? So when the torch has a version for it, it is already in plan for us

**Comment by edgarriba** [comment]
Working on this these days

**Comment by johnnv1** [comment]
Done on 0.0.8 version
