### ISSUE TITLE
Automate the packaging for manywheels in the ci.yml

### ISSUE THREAD

**Issue by edgarriba** [kornia/kornia-rs#3]

**Comment by carlosb1** [comment]
First step could be the creation of the ci.yml file and check that it can run.. for the packaging, it implies to include a cargo publish with the crates.io credentials...

**Comment by carlosb1** [comment]
Some example about how can we do this?

**Comment by edgarriba** [comment]
now I did by hand using the `build_wheels.sh` script with this docker container https://github.com/kornia/kornia-rs/blob/main/docker/release.Dockerfile

Also followed the examples in https://github.com/PyO3/maturin#manylinux-and-auditwheel

**Comment by carlosb1** [comment]
I am not sure but it seems that this task was done, I check the release.yml and it has the ' messense/maturin-action@v1' git action for applying manywheels.

**Comment by edgarriba** [comment]
It's not activated, there were some issues with the docker environment. Right now I was doing the releases by hand with support only for Linux. Would be great if you can explore that using the dockerfile for release and automate every time we publish a release that builds and push the wheels to pip

**Comment by edgarriba** [comment]
finalized in 38bd63a4ec83589a41d6e89b8011fb48f9248f4e
