### ISSUE TITLE
add releases with m1 macos support

### ISSUE THREAD

**Issue by johnnv1** [kornia/kornia-rs#36]
Integrate the new gh action runner to build the package within m1 macos support 

https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

Related to https://github.com/kornia/kornia/pull/2775 -- without this, we won't have support for `kornia.io` under m1 (`mps`) devices

**Comment by johnnv1** [comment]
@edgarriba it's solved here https://github.com/kornia/kornia-rs/blob/06f929b593dc97f6d9ab2e8bd103b11d12a0d1fa/.github/workflows/python_release.yml#L62, right?

**Comment by edgarriba** [comment]
I believe it’s that, let’s mark as solved. Reopen if any m1 reports the contrary
