### ISSUE TITLE
[Bug] Cannot open JPEG image

### ISSUE THREAD

**Issue by ternaus** [kornia/kornia-rs#40]
```bash
  File "/mnt/evo850/workspace/imread_benchmark/imread_benchmark/benchmark.py", line 114, in kornia
    return K.read_image_jpeg(image_path)
FileExistsError: File is not a JPEG: /mnt/evo970/data/Imagenet1k/ILSVRC2015/Data/CLS-LOC/val/ILSVRC2012_val_00000001.JPEG
```

**Comment by ternaus** [comment]
Image that Kornia-rs cannot open:

![ILSVRC2012_val_00000001](https://github.com/kornia/kornia-rs/assets/5481618/133996d0-2613-4540-9ad0-bdc52cbe1896)

**Comment by edgarriba** [comment]
Thanks to report, the current implementation expects image paths with the file extension in lower case. I’ll fix that soon

**Comment by ternaus** [comment]
Thanks!
