### ISSUE TITLE
Release sdist on PyPI

### ISSUE THREAD

**Issue by adamjstewart** [kornia/kornia-rs#49]
PyPI only has a bdist (.whl). Can you also release an sdist (.tar.gz)? This is useful for package managers that require stable checksums.

**Comment by edgarriba** [comment]
sure -- i'll look into it for the next release

**Comment by edgarriba** [comment]
ok, i think #50 might do the thing. Locally tested and seems to produce the tar correctly. It does include also all the rust source in case anyone wants to reproduce the build. I'll merge and we;ll see in the next release when i add new features if it worked well.
